{
 "title": "Banking Microservices",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Used Heap",
   "type": "graph",
   "description": "Heap used by each application,  averaged across all instances",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(base_memory_usedHeap_bytes{job=\"transaction-service\"})",
     "legendFormat": "Transaction Service"
    },
    {
     "expr": "avg(base_memory_usedHeap_bytes{job=\"account-service\"})",
     "legendFormat": "Account Service"
    }
   ]
  },
  {
   "title": "Account service ErrorMapper calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_quarkus_accounts_AccountResource_ErrorMapper_ErrorMapperCounter_total",
     "legendFormat": "ErrorMapper calls"
    }
   ]
  },
  {
   "title": "Transaction Service - Fallback Count by HTTP Status Code",
   "type": "graph",
   "description": "Fallback count by HTTP status Code, averaged across all instances",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(application_fallback_total{http_status_code=\"429\"})",
     "legendFormat": "Too Many Requests (429)"
    },
    {
     "expr": "avg(application_fallback_total{http_status_code=\"504\"})",
     "legendFormat": "Gateway Timeout (504)"
    },
    {
     "expr": "avg(application_fallback_total{http_status_code=\"503\"})",
     "legendFormat": "Service Unavailable (503)"
    },
    {
     "expr": "avg(application_fallback_total{http_status_code=\"502\"})",
     "legendFormat": "Bad Gateway (502)"
    },
    {
     "expr": "avg(application_fallback_total{http_status_code=\"501\"})",
     "legendFormat": "Not Implemented (501)"
    }
   ]
  },
  {
   "title": "Transaction Service Concurrent Blocking Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_concurrentBlockingTransactions_current",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction Service - Deposits Distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "avg(application_io_quarkus_transactions_TransactionResource_deposits{quantile=\"0.5\"})",
     "legendFormat": "Quantile .5"
    },
    {
     "expr": "avg(application_io_quarkus_transactions_TransactionResource_deposits{quantile=\"0.75\"})",
     "legendFormat": "Quantile .75"
    },
    {
     "expr": "avg(application_io_quarkus_transactions_TransactionResource_deposits{quantile=\"0.95\"})",
     "legendFormat": "Quantile .95"
    },
    {
     "expr": "avg(application_io_quarkus_transactions_TransactionResource_deposits{quantile=\"0.99\"})",
     "legendFormat": "Quantile .99"
    }
   ]
  },
  {
   "title": "Transaction Service - Fallback Call Rate Rolling One Minute Average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " avg(application_fallbackHandlerTimer_one_min_rate_per_second)"
    }
   ]
  }
 ]
}