apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: transaction-service
  namespace: default
  labels:
    app.kubernetes.io/name: transaction-service
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: transaction-service
  endpoints:
  - port: http
    interval: 3s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: account-service
  namespace: default
  labels:
    app.kubernetes.io/name: account-service
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: account-service
  endpoints:
  - port: http
    interval: 3s
